linkWorkspacePackages: true

preferWorkspacePackages: true

shellEmulator: true

trustPolicy: no-downgrade

reporter: silent
packages:
  - mc-tools/packages/*
onlyBuiltDependencies:
  - '@vscode/vsce-sign'
  - cpu-features
  - es5-ext
  - esbuild
  - keytar
  - node-pty
  - puppeteer
  - ssh2
