#modloaded immersiveengineering
#priority -3000

import crafttweaker.item.IItemStack;

import native.blusunrize.immersiveengineering.common.crafting.ArcRecyclingRecipe;
import native.blusunrize.immersiveengineering.api.crafting.ArcFurnaceRecipe;
import native.java.util.HashMap;

function add(input as IItemStack, outputs as double[IItemStack], time as int = 100, energy as int = 512) as void {
  val map as HashMap = HashMap();
  for stack, chance in outputs {
    map.put(stack.native, chance);
  }
  ArcFurnaceRecipe.recipeList.add(ArcRecyclingRecipe(map, input.native, time, energy));
}

add(<advancedrocketry:jackhammer:*>, { <minecraft:iron_ingot>: 0.5, <thermalfoundation:material:132>: 2.0 });
add(<advancedrocketry:spaceboots:*>, { <libvulpes:productingot:7>: 2.0 });
add(<advancedrocketry:spacechestplate:*>, { <libvulpes:productingot:7>: 1.0, <thermalfoundation:material:160>: 1.0 });
add(<advancedrocketry:spacehelmet:*>, { <libvulpes:productingot:7>: 2.0 });
add(<advancedrocketry:spaceleggings:*>, { <libvulpes:productingot:7>: 1.0 });
add(<astralsorcery:itemcape:*>, { <minecraft:iron_ingot>: 0.003907203674316406 });
add(<avaritia:infinity_axe:*>, { <avaritia:resource:4>: 6.0, <avaritia:resource:6>: 6.0 });
add(<avaritia:infinity_boots:*>, { <avaritia:resource:4>: 32.0, <avaritia:resource:6>: 8.0 });
add(<avaritia:infinity_chestplate:*>, { <avaritia:resource:4>: 31.0, <avaritia:resource:6>: 21.0 });
add(<avaritia:infinity_helmet:*>, { <astralsorcery:itemcraftingcomponent:1>: 9.0, <avaritia:resource:1>: 9.0, <avaritia:resource:4>: 15.0, <avaritia:resource:6>: 15.0, <extrautils2:ingredients:17>: 9.0, <thermalfoundation:material:167>: 9.0 });
add(<avaritia:infinity_hoe:*>, { <avaritia:resource:4>: 6.0, <avaritia:resource:6>: 11.0 });
add(<avaritia:infinity_pants:*>, { <astralsorcery:itemcraftingcomponent:1>: 9.0, <avaritia:resource:1>: 9.0, <avaritia:resource:4>: 42.0, <avaritia:resource:6>: 14.0, <extrautils2:ingredients:17>: 9.0, <thermalfoundation:material:167>: 9.0 });
add(<avaritia:infinity_pickaxe:*>.withTag({ ench: [{ lvl: 10 as short, id: 35 as short }] }), { <avaritia:resource:1>: 9.0, <avaritia:resource:4>: 6.0, <avaritia:resource:6>: 15.0 });
add(<avaritia:infinity_shovel:*>, { <avaritia:resource:4>: 6.0, <avaritia:resource:6>: 14.0 });
add(<avaritia:infinity_sword:*>, { <astralsorcery:itemcraftingcomponent:1>: 4.5, <avaritia:resource:1>: 40.5, <avaritia:resource:6>: 11.0, <extrautils2:ingredients:17>: 4.5 });
add(<avaritia:skullfire_sword:*>, { <minecraft:netherbrick>: 2.0 });
add(<bibliocraft:biblioglasses:1>, { <minecraft:iron_ingot>: 0.5 });
add(<bibliocraft:biblioglasses:2>, { <minecraft:gold_ingot>: 0.4444444444444444 });
add(<bibliocraft:biblioglasses>, { <minecraft:iron_ingot>: 1.0 });
add(<bloodmagic:pack_sacrifice:*>, { <minecraft:iron_ingot>: 1.5, <thermalfoundation:material:162>: 2.0 });
add(<botania:elementiumaxe:*>, { <botania:manaresource:7>: 3.0 });
add(<botania:elementiumboots:*>, { <botania:manaresource:7>: 5.0 });
add(<botania:elementiumchest:*>, { <botania:manaresource:7>: 8.0 });
add(<botania:elementiumhelm:*>, { <botania:manaresource:7>: 5.0 });
add(<botania:elementiumhelmreveal:*>, { <botania:manaresource:7>: 2.5, <thaumcraft:ingot:2>: 1.0, <thermalfoundation:material:128>: 2.0 });
add(<botania:elementiumlegs:*>, { <botania:manaresource:7>: 7.0 });
add(<botania:enderdagger:*>, { <botania:manaresource>: 1.0 });
add(<botania:manasteelboots:*>, { <botania:manaresource>: 5.0 });
add(<botania:manasteelchest:*>, { <botania:manaresource>: 8.0 });
add(<botania:manasteelhelm:*>, { <botania:manaresource>: 5.0 });
add(<botania:manasteelhelmreveal:*>, { <botania:manaresource>: 2.5, <thaumcraft:ingot:2>: 1.0, <thermalfoundation:material:128>: 2.0 });
add(<botania:manasteellegs:*>, { <botania:manaresource>: 7.0 });
add(<botania:starsword:*>, { <botania:manaresource:4>: 1.0, <botania:manaresource:7>: 1.0 });
add(<botania:terraaxe:*>, { <botania:manaresource:4>: 3.0 });
add(<botania:terrapick:*>, { <botania:manaresource:4>: 4.0 });
add(<botania:terrasteelboots:*>, { <botania:manaresource:4>: 3.0, <botania:manaresource:7>: 2.5 });
add(<botania:terrasteelchest:*>, { <botania:manaresource:4>: 5.0, <botania:manaresource:7>: 4.0 });
add(<botania:terrasteelhelm:*>, { <botania:manaresource:4>: 3.0, <botania:manaresource:7>: 2.5 });
add(<botania:terrasteelhelmreveal:*>, { <botania:manaresource:4>: 3.0, <botania:manaresource>: 1.25, <thaumcraft:ingot:2>: 0.5, <thermalfoundation:material:128>: 1.0 });
add(<botania:terrasteellegs:*>, { <botania:manaresource:4>: 3.0, <botania:manaresource:7>: 3.5 });
add(<botania:terrasword:*>, { <botania:manaresource:4>: 2.0 });
add(<botania:thundersword:*>, { <botania:manaresource:4>: 1.0, <botania:manaresource:7>: 1.0 });
add(<compactsolars:solar_hat_high_voltage>, { <minecraft:iron_ingot>: 0.125 });
add(<compactsolars:solar_hat_low_voltage>, { <minecraft:iron_ingot>: 9.0 });
add(<compactsolars:solar_hat_medium_voltage>, { <minecraft:iron_ingot>: 36.0 });
add(<cyclicmagic:sword_ender:*>.withTag({ ench: [{ lvl: 1 as short, id: 64 as short }] }), { <minecraft:iron_ingot>: 1.0 });
add(<cyclicmagic:sword_slowness:*>.withTag({ ench: [{ lvl: 1 as short, id: 64 as short }] }), { <minecraft:iron_ingot>: 1.0 });
add(<cyclicmagic:sword_weakness:*>.withTag({ ench: [{ lvl: 1 as short, id: 64 as short }] }), { <minecraft:iron_ingot>: 1.0 });
add(<enderio:item_dark_steel_axe:*>, { <enderio:item_alloy_ingot:6>: 3.0 });
add(<enderio:item_dark_steel_boots:*>, { <enderio:item_alloy_ingot:5>: 0.44444444444444453, <enderio:item_alloy_ingot:6>: 4.0 });
add(<enderio:item_dark_steel_chestplate:*>, { <enderio:item_alloy_ingot:5>: 0.44444444444444453, <enderio:item_alloy_ingot:6>: 7.0 });
add(<enderio:item_dark_steel_crook:*>, { <enderio:item_alloy_ingot:6>: 2.0 });
add(<enderio:item_dark_steel_helmet:*>, { <enderio:item_alloy_ingot:5>: 0.44444444444444453, <enderio:item_alloy_ingot:6>: 4.0 });
add(<enderio:item_dark_steel_leggings:*>, { <enderio:item_alloy_ingot:5>: 0.44444444444444453, <enderio:item_alloy_ingot:6>: 6.0 });
add(<enderio:item_dark_steel_pickaxe:*>, { <enderio:item_alloy_ingot:6>: 3.0 });
add(<enderio:item_dark_steel_sword:*>, { <enderio:item_alloy_ingot:6>: 2.0 });
add(<enderio:item_end_steel_axe:*>, { <enderio:item_alloy_ingot:6>: 0.4444444444444444, <enderio:item_alloy_ingot:8>: 3.0 });
add(<enderio:item_end_steel_boots:*>, { <enderio:item_alloy_ingot:1>: 1.0, <enderio:item_alloy_ingot:8>: 4.0, <libvulpes:productingot:3>: 1.0 });
add(<enderio:item_end_steel_chestplate:*>, { <enderio:item_alloy_ingot:1>: 1.0, <enderio:item_alloy_ingot:8>: 7.0, <libvulpes:productingot:3>: 1.0 });
add(<enderio:item_end_steel_helmet:*>, { <enderio:item_alloy_ingot:1>: 1.0, <enderio:item_alloy_ingot:8>: 4.0, <libvulpes:productingot:3>: 1.0 });
add(<enderio:item_end_steel_leggings:*>, { <enderio:item_alloy_ingot:1>: 1.0, <enderio:item_alloy_ingot:8>: 6.0, <libvulpes:productingot:3>: 1.0 });
add(<enderio:item_end_steel_pickaxe:*>, { <enderio:item_alloy_ingot:6>: 0.4444444444444444, <enderio:item_alloy_ingot:8>: 3.0 });
add(<enderio:item_end_steel_sword:*>, { <enderio:item_alloy_ingot:6>: 0.2222222222222222, <enderio:item_alloy_ingot:8>: 2.0 });
add(<enderio:item_stellar_alloy_axe:*>, { <enderio:item_alloy_endergy_ingot:3>: 3.0, <enderio:item_alloy_ingot:6>: 0.2222222222222222 });
add(<enderio:item_stellar_alloy_boots:*>, { <enderio:item_alloy_endergy_ingot:3>: 4.0 });
add(<enderio:item_stellar_alloy_chestplate:*>, { <enderio:item_alloy_endergy_ingot:3>: 7.0 });
add(<enderio:item_stellar_alloy_helmet:*>, { <enderio:item_alloy_endergy_ingot:3>: 4.0 });
add(<enderio:item_stellar_alloy_leggings:*>, { <enderio:item_alloy_endergy_ingot:3>: 6.0 });
add(<enderio:item_stellar_alloy_pickaxe:*>, { <enderio:item_alloy_endergy_ingot:3>: 3.0, <enderio:item_alloy_ingot:6>: 0.2222222222222222 });
add(<enderio:item_stellar_alloy_sword:*>, { <enderio:item_alloy_endergy_ingot:3>: 2.0 });
add(<endreborn:armour_boots_dragon:*>, { <endreborn:item_ingot_endorium>: 1.0, <mysticalagriculture:crafting:32>: 0.027777777777777776 });
add(<endreborn:armour_chestplate_dragon:*>, { <endreborn:item_ingot_endorium>: 1.0, <mysticalagriculture:crafting:32>: 0.027777777777777776 });
add(<endreborn:armour_helmet_dragon:*>, { <endreborn:item_ingot_endorium>: 1.0, <mysticalagriculture:crafting:32>: 0.027777777777777776 });
add(<endreborn:armour_leggings_dragon:*>, { <endreborn:item_ingot_endorium>: 1.0, <mysticalagriculture:crafting:32>: 0.027777777777777776 });
add(<endreborn:ender_sword:*>.withTag({ ench: [{ lvl: 1 as short, id: 64 as short }] }), { <endreborn:item_ingot_endorium>: 6.0, <mysticalagriculture:crafting:32>: 0.027777777777777776 });
add(<endreborn:tool_magnifier:*>, { <endreborn:item_ingot_endorium>: 1.0, <qmd:ingot>: 1.0 });
add(<extrautils2:fireaxe>, { <minecraft:gold_ingot>: 27.0, <minecraft:iron_ingot>: 28.0 });
add(<extrautils2:lawsword>, { <minecraft:gold_ingot>: 18.0, <minecraft:iron_ingot>: 1.0 });
add(<extrautils2:luxsaber:1>, { <extrautils2:ingredients:17>: 6.0 });
add(<extrautils2:luxsaber:2>, { <extrautils2:ingredients:17>: 6.0 });
add(<extrautils2:luxsaber:3>, { <extrautils2:ingredients:17>: 6.0 });
add(<extrautils2:luxsaber:4>, { <extrautils2:ingredients:17>: 6.0 });
add(<extrautils2:luxsaber:5>, { <extrautils2:ingredients:17>: 6.0 });
add(<extrautils2:luxsaber:6>, { <extrautils2:ingredients:17>: 6.0 });
add(<extrautils2:luxsaber:7>, { <extrautils2:ingredients:17>: 6.0 });
add(<extrautils2:luxsaber>, { <extrautils2:ingredients:17>: 6.0 });
add(<extrautils2:sickle_gold:*>, { <minecraft:gold_ingot>: 5.0 });
add(<extrautils2:sickle_iron:*>, { <minecraft:iron_ingot>: 5.0 });
add(<forestry:naturalist_helmet:*>, { <thermalfoundation:material:163>: 1.0 });
add(<gendustry:industrial_grafter:*>, { <thermalfoundation:material:163>: 8.5 });
add(<gendustry:industrial_scoop:*>, { <thermalfoundation:material:163>: 8.0 });
add(<ic2:advanced_batpack:*>, { <minecraft:iron_ingot>: 0.5 });
add(<ic2:batpack:*>, { <minecraft:iron_ingot>: 0.5 });
add(<ic2:cf_pack:*>, { <minecraft:iron_ingot>: 0.5 });
add(<ic2:chainsaw:*>, { <minecraft:iron_ingot>: 6.75 });
add(<ic2:crowbar:*>, { <thermalfoundation:material:163>: 3.0 });
add(<ic2:diamond_drill:*>, { <thermalfoundation:material:132>: 2.0 });
add(<ic2:drill:*>, { <minecraft:iron_ingot>: 6.75 });
add(<ic2:electric_hoe:*>, { <minecraft:iron_ingot>: 3.75 });
add(<ic2:electric_treetap:*>, { <minecraft:iron_ingot>: 0.75 });
add(<ic2:energy_pack:*>, { <minecraft:iron_ingot>: 0.5 });
add(<ic2:iridium_drill:*>, { <thermalfoundation:material:135>: 6.0 });
add(<ic2:jetpack:*>, { <minecraft:iron_ingot>: 1.0 });
add(<ic2:jetpack_electric:*>, { <minecraft:iron_ingot>: 1.0 });
add(<ic2:mining_laser:*>, { <minecraft:iron_ingot>: 0.25 });
add(<ic2:nano_boots:*>, { <advancedrocketry:misc:1>: 4.0 });
add(<ic2:nano_chestplate:*>, { <advancedrocketry:misc:1>: 7.0 });
add(<ic2:nano_helmet:*>, { <advancedrocketry:misc:1>: 4.0 });
add(<ic2:nano_leggings:*>, { <advancedrocketry:misc:1>: 6.0 });
add(<ic2:nano_saber:*>, { <advancedrocketry:misc:1>: 2.0 });
add(<ic2:nightvision_goggles:*>, { <minecraft:iron_ingot>: 1.25, <thermalfoundation:material:128>: 1.0 });
add(<ic2:quantum_boots:*>, { <thermalfoundation:material:135>: 4.0 });
add(<ic2:quantum_chestplate:*>, { <thermalfoundation:material:135>: 4.0 });
add(<ic2:quantum_helmet:*>, { <thermalfoundation:material:135>: 4.0 });
add(<ic2:quantum_leggings:*>, { <thermalfoundation:material:135>: 4.0 });
add(<ic2:solar_helmet>, { <minecraft:iron_ingot>: 2.25 });
add(<ic2:wind_meter:*>, { <minecraft:iron_ingot>: 0.75 });
add(<ic2:wrench_new:*>, { <thermalfoundation:material:163>: 6.0 });
add(<iceandfire:dragonsteel_fire_boots:*>, { <iceandfire:dragonsteel_fire_ingot>: 4.0 });
add(<iceandfire:dragonsteel_fire_chestplate:*>, { <iceandfire:dragonsteel_fire_ingot>: 8.0 });
add(<iceandfire:dragonsteel_fire_helmet:*>, { <iceandfire:dragonsteel_fire_ingot>: 5.0 });
add(<iceandfire:dragonsteel_fire_leggings:*>, { <iceandfire:dragonsteel_fire_ingot>: 7.0 });
add(<iceandfire:dragonsteel_ice_boots:*>, { <iceandfire:dragonsteel_ice_ingot>: 4.0 });
add(<iceandfire:dragonsteel_ice_chestplate:*>, { <iceandfire:dragonsteel_ice_ingot>: 8.0 });
add(<iceandfire:dragonsteel_ice_helmet:*>, { <iceandfire:dragonsteel_ice_ingot>: 5.0 });
add(<iceandfire:dragonsteel_ice_leggings:*>, { <iceandfire:dragonsteel_ice_ingot>: 7.0 });
add(<iceandfire:hippogryph_sword:*>, { <minecraft:iron_ingot>: 1.0 });
add(<immersiveengineering:drillhead:1>, { <minecraft:iron_ingot>: 23.0 });
add(<immersiveengineering:drillhead>, { <thermalfoundation:material:160>: 23.0 });
add(<immersiveengineering:metal_decoration0:1>, { <minecraft:iron_ingot>: 1.0 });
add(<immersiveengineering:metal_decoration0:2>, { <minecraft:iron_ingot>: 1.0 });
add(<immersiveengineering:metal_decoration0:3> * 2, { <thermalfoundation:material:128>: 2.0, <thermalfoundation:material:164>: 2.0 });
add(<immersiveengineering:metal_decoration0:3> * 4, { <thermalfoundation:material:128>: 1.0, <thermalfoundation:material:164>: 1.0, <thermalfoundation:material:165>: 0.25 });
add(<immersiveengineering:metal_decoration0:4> * 4, { <thermalfoundation:material:163>: 1.0 });
add(<immersiveengineering:metal_decoration0:4> * 6, { <enderio:item_alloy_ingot:3>: 0.6666666666666666, <thermalfoundation:material:164>: 0.6666666666666666 });
add(<immersiveengineering:metal_decoration0:5> * 10, { <thermalfoundation:material:128>: 0.1, <thermalfoundation:material:160>: 0.4 });
add(<immersiveengineering:metal_decoration0:5> * 4, { <immersiveengineering:metal:5>: 1.0, <minecraft:iron_ingot>: 1.0, <thermalfoundation:material:128>: 0.25 });
add(<immersiveengineering:metal_decoration0:6> * 2, { <minecraft:iron_ingot>: 0.875, <thermalfoundation:material:160>: 3.0, <thermalfoundation:material:161>: 1.0 });
add(<immersiveengineering:metal_decoration0:7> * 2, { <minecraft:iron_ingot>: 0.375, <thermalfoundation:material:128>: 2.0, <thermalfoundation:material:160>: 2.0 });
add(<immersiveengineering:metal_decoration0>, { <minecraft:iron_ingot>: 1.0 });
add(<immersiveengineering:metal_decoration1:1> * 24, { <thermalfoundation:material:160>: 0.125 });
add(<immersiveengineering:metal_decoration1:4> * 12, { <thermalfoundation:material:132>: 0.3333333333333333 });
add(<immersiveengineering:metal_decoration1:5> * 24, { <thermalfoundation:material:132>: 0.125 });
add(<immersiveengineering:metal_decoration1> * 12, { <thermalfoundation:material:160>: 0.3333333333333333 });
add(<immersiveengineering:metal_decoration2:1> * 4, { <thermalfoundation:material:160>: 0.75 });
add(<immersiveengineering:metal_decoration2:2>, { <thermalfoundation:material:132>: 3.3333333333333335 });
add(<immersiveengineering:metal_decoration2:3> * 4, { <thermalfoundation:material:132>: 0.75 });
add(<immersiveengineering:metal_decoration2:4> * 3, { <minecraft:iron_ingot>: 0.6666666666666666 });
add(<immersiveengineering:metal_decoration2:5> * 3, { <thermalfoundation:material:160>: 2.1666666666666665 });
add(<immersiveengineering:metal_decoration2>, { <thermalfoundation:material:160>: 3.3333333333333335 });
add(<immersiveengineering:metal_device0:1>, { <minecraft:iron_ingot>: 0.5, <thermalfoundation:material:161>: 1.0 });
add(<immersiveengineering:metal_device0:2>, { <minecraft:iron_ingot>: 0.25, <thermalfoundation:material:161>: 0.5 });
add(<immersiveengineering:metal_device0:5>, { <minecraft:iron_ingot>: 5.0, <thermalfoundation:material:128>: 0.5 });
add(<immersiveengineering:metal_device0:6>, { <minecraft:iron_ingot>: 4.0 });
add(<immersiveengineering:metal_device0>, { <minecraft:iron_ingot>: 1.0 });
add(<immersiveengineering:metal_device1:10>, { <minecraft:iron_ingot>: 0.5, <thermalfoundation:material:128>: 2.0 });
add(<immersiveengineering:metal_device1:11>, { <minecraft:iron_ingot>: 3.25, <thermalfoundation:material:128>: 4.875, <thermalfoundation:material:160>: 2.75 });
add(<immersiveengineering:metal_device1:1>, { <minecraft:iron_ingot>: 4.5, <thermalfoundation:material:128>: 3.0 });
add(<immersiveengineering:metal_device1:2>, { <minecraft:iron_ingot>: 3.5 });
add(<immersiveengineering:metal_device1:3>, { <minecraft:iron_ingot>: 0.5, <thermalfoundation:material:160>: 3.0, <thermalfoundation:material:164>: 5.0 });
add(<immersiveengineering:metal_device1:4> * 3, { <minecraft:iron_ingot>: 1.3333333333333333, <thermalfoundation:material:128>: 0.16666666666666666 });
add(<immersiveengineering:metal_device1:5>, { <minecraft:iron_ingot>: 3.0 });
add(<immersiveengineering:metal_device1:6> * 32, { <minecraft:iron_ingot>: 0.1875 });
add(<immersiveengineering:metal_device1:7>, { <thermalfoundation:material:160>: 5.0 });
add(<immersiveengineering:metal_device1:8>, { <minecraft:iron_ingot>: 1.25, <thermalfoundation:material:132>: 3.0, <thermalfoundation:material:161>: 0.5 });
add(<immersiveengineering:metal_device1:9> * 3, { <minecraft:iron_ingot>: 0.6666666666666666, <thermalfoundation:material:128>: 0.16666666666666666 });
add(<immersiveengineering:metal_device1>, { <minecraft:iron_ingot>: 2.25, <thermalfoundation:material:128>: 1.5 });
add(<immersiveengineering:powerpack>, { <thermalfoundation:material:131>: 1.0 });
add(<immersiveengineering:wirecoil:1> * 4, { <thermalfoundation:material:161>: 0.5 });
add(<immersiveengineering:wirecoil:2> * 4, { <thermalfoundation:material:132>: 0.25, <thermalfoundation:material:160>: 0.25 });
add(<immersiveengineering:wirecoil:4> * 4, { <thermalfoundation:material:160>: 0.5 });
add(<immersiveengineering:wirecoil:5> * 4, { <thermalfoundation:material:132>: 0.25 });
add(<immersiveengineering:wirecoil:7> * 4, { <minecraft:iron_ingot>: 0.1875 });
add(<immersiveengineering:wirecoil> * 4, { <thermalfoundation:material:128>: 0.5 });
add(<kami:awakened_ichorium_axe>.withTag({ mode: 0, Unbreakable: 1 as byte }), { <botania:manaresource>: 1.0, <extrautils2:ingredients:11>: 1.0, <kami:ichorium_ingot>: 1.5, <thaumadditions:mithminite_ingot>: 1.0, <thaumcraft:quicksilver>: 0.5 });
add(<kami:awakened_ichorium_pickaxe>.withTag({ mode: 0, Unbreakable: 1 as byte, infench: [{ lvl: 4 as short, id: 4 as short }] }), { <kami:ichorium_ingot>: 2.0, <thaumadditions:mithminite_ingot>: 1.0 });
add(<kami:awakened_ichorium_shovel>.withTag({ mode: 0, Unbreakable: 1 as byte }), { <kami:ichorium_ingot>: 1.0, <thaumadditions:mithminite_ingot>: 1.0 });
add(<kami:awakened_ichorium_sword>.withTag({ Unbreakable: 1 as byte, infench: [{ lvl: 4 as short, id: 5 as short }] }), { <thaumadditions:mithminite_ingot>: 1.0 });
add(<kami:awakened_ichorweave_boots>, { <minecraft:gold_ingot>: 1.0, <thaumcraft:ingot:1>: 0.5, <thaumcraft:quicksilver>: 0.25 });
add(<kami:awakened_ichorweave_hood>, { <thaumcraft:ingot:1>: 0.75 });
add(<kami:awakened_ichorweave_leggings>, { <thaumcraft:ingot:1>: 1.25, <thaumcraft:ingot>: 0.25 });
add(<kami:awakened_ichorweave_robe>, { <minecraft:iron_ingot>: 1.0, <thaumcraft:ingot:1>: 1.0, <thaumcraft:ingot:2>: 0.9861111111111112, <thaumcraft:ingot>: 0.25 });
add(<kami:ichorium_axe>.withTag({ Unbreakable: 1 as byte }), { <kami:ichorium_ingot>: 3.0, <thaumcraft:quicksilver>: 1.0 });
add(<kami:ichorium_pickaxe>.withTag({ Unbreakable: 1 as byte, infench: [{ lvl: 4 as short, id: 4 as short }] }), { <kami:ichorium_ingot>: 4.0 });
add(<kami:ichorium_shovel>.withTag({ Unbreakable: 1 as byte }), { <kami:ichorium_ingot>: 2.0 });
add(<kami:ichorium_sword>.withTag({ Unbreakable: 1 as byte }), { <kami:ichorium_ingot>: 2.0, <thaumcraft:quicksilver>: 0.5 });
add(<kami:ichorweave_boots>, { <thaumcraft:ingot:1>: 1.0, <thaumcraft:quicksilver>: 0.5 });
add(<kami:ichorweave_hood>, { <thaumcraft:ingot:1>: 1.5, <thaumcraft:ingot>: 0.25 });
add(<kami:ichorweave_leggings>, { <thaumcraft:ingot:1>: 2.5, <thaumcraft:ingot:2>: 0.125, <thaumcraft:ingot>: 0.5 });
add(<kami:ichorweave_robe>, { <thaumcraft:ingot:1>: 2.0, <thaumcraft:ingot>: 0.5 });
add(<mekanism:armoredjetpack>.withTag({  }), { <thermalfoundation:material:160>: 9.0, <thermalfoundation:material:163>: 2.0 });
add(<mekanism:freerunners>, { <minecraft:gold_ingot>: 3.0, <minecraft:iron_ingot>: 1.0 });
add(<mekanism:gasmask>, { <minecraft:iron_ingot>: 0.5, <thermalfoundation:material:160>: 3.0 });
add(<mekanism:jetpack>, { <thermalfoundation:material:160>: 2.0, <thermalfoundation:material:163>: 4.0 });
add(<mekanism:scubatank>.withTag({  }), { <mekanism:ingot:1>: 1.0, <minecraft:iron_ingot>: 0.5, <thermalfoundation:material:160>: 3.0 });
add(<minecraft:golden_axe:*>, { <minecraft:gold_ingot>: 3.0 });
add(<minecraft:golden_hoe:*>, { <minecraft:gold_ingot>: 2.0 });
add(<minecraft:golden_pickaxe:*>, { <minecraft:gold_ingot>: 3.0 });
add(<minecraft:golden_shovel:*>, { <minecraft:gold_ingot>: 1.0 });
add(<minecraft:golden_sword:*>, { <minecraft:gold_ingot>: 2.0 });
add(<minecraft:iron_axe:*>, { <minecraft:iron_ingot>: 3.0 });
add(<minecraft:iron_hoe:*>, { <minecraft:iron_ingot>: 2.0 });
add(<minecraft:iron_pickaxe:*>, { <minecraft:iron_ingot>: 3.0 });
add(<minecraft:iron_shovel:*>, { <minecraft:iron_ingot>: 1.0 });
add(<minecraft:iron_sword:*>, { <minecraft:iron_ingot>: 2.0 });
add(<mysticalagriculture:soulium_dagger:*>, { <mysticalagriculture:crafting:38>: 2.0 });
add(<openblocks:crane_backpack:*>, { <minecraft:iron_ingot>: 9.0 });
add(<openblocks:sonic_glasses:*>, { <minecraft:iron_ingot>: 2.0 });
add(<opencomputers:hoverboots:*>, { <minecraft:gold_ingot>: 0.2222222222222222, <minecraft:iron_ingot>: 0.9444444444444446 });
add(<plethora:neuralinterface>, { <minecraft:gold_ingot>: 2.0, <minecraft:iron_ingot>: 1.0 });
add(<psi:psimetal_axe:*>, { <minecraft:iron_ingot>: 2.0, <psi:material:1>: 2.0 });
add(<psi:psimetal_exosuit_boots:*>, { <psi:material:1>: 4.0 });
add(<psi:psimetal_exosuit_chestplate:*>, { <psi:material:1>: 7.0 });
add(<psi:psimetal_exosuit_helmet:*>, { <psi:material:1>: 4.0 });
add(<psi:psimetal_exosuit_leggings:*>, { <psi:material:1>: 6.0 });
add(<psi:psimetal_pickaxe:*>, { <minecraft:iron_ingot>: 2.0, <psi:material:1>: 2.0 });
add(<psi:psimetal_shovel:*>, { <minecraft:iron_ingot>: 2.0, <psi:material:1>: 1.0 });
add(<psi:psimetal_sword:*>, { <minecraft:iron_ingot>: 1.0, <psi:material:1>: 1.0 });
add(<qmd:boots_hev>, { <nuclearcraft:alloy:1>: 1.0, <nuclearcraft:uranium:10>: 4.0 });
add(<qmd:chest_hev>, { <nuclearcraft:alloy:1>: 1.0, <nuclearcraft:uranium:10>: 4.0 });
add(<qmd:helm_hev>, { <nuclearcraft:alloy:1>: 1.0, <nuclearcraft:uranium:10>: 4.0 });
add(<qmd:legs_hev>, { <nuclearcraft:alloy:1>: 1.0, <nuclearcraft:uranium:10>: 4.0 });
add(<quark:backpack>, { <tconstruct:ingots:5>: 1.0 });
add(<rats:plague_scythe:*>, { <thaumadditions:mithminite_ingot>: 2.25 });
add(<redstonearsenal:armor.boots_flux>, { <redstonearsenal:material:32>: 10.0 });
add(<redstonearsenal:armor.helmet_flux>, { <redstonearsenal:material:32>: 10.0 });
add(<redstonearsenal:armor.legs_flux>, { <redstonearsenal:material:32>: 14.0 });
add(<redstonearsenal:armor.plate_flux>, { <redstonearsenal:material:32>: 16.0 });
add(<redstonearsenal:tool.axe_flux>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 3.0 });
add(<redstonearsenal:tool.battlewrench_flux>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 6.0 });
add(<redstonearsenal:tool.excavator_flux>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 3.0 });
add(<redstonearsenal:tool.hammer_flux>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 5.0 });
add(<redstonearsenal:tool.pickaxe_flux>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 3.0 });
add(<redstonearsenal:tool.shovel_flux>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 1.0 });
add(<redstonearsenal:tool.sickle_flux>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 3.0 });
add(<redstonearsenal:tool.sword_flux>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 2.0 });
add(<redstonerepository:armor.boots_gelid>.withTag({ Energy: 0 }), { <redstonerepository:material:1>: 8.0 });
add(<redstonerepository:armor.chestplategelid>.withTag({ Energy: 0 }), { <redstonerepository:material:1>: 16.0 });
add(<redstonerepository:armor.helmet_gelid>.withTag({ Energy: 0 }), { <redstonerepository:material:1>: 10.0 });
add(<redstonerepository:armor.leggings_gelid>.withTag({ Energy: 0 }), { <redstonerepository:material:1>: 14.0 });
add(<redstonerepository:tool.axe_gelid>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 1.5, <redstonerepository:material:1>: 3.0 });
add(<redstonerepository:tool.battlewrench_gelid>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 3.0, <redstonerepository:material:1>: 6.0 });
add(<redstonerepository:tool.excavator_gelid>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 1.5, <redstonerepository:material:1>: 3.0 });
add(<redstonerepository:tool.hammer_gelid>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 2.5, <redstonerepository:material:1>: 5.0 });
add(<redstonerepository:tool.pickaxe_gelid>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 1.5, <redstonerepository:material:1>: 3.0 });
add(<redstonerepository:tool.shovel_gelid>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 0.5, <redstonerepository:material:1>: 1.0 });
add(<redstonerepository:tool.sickle_gelid>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 1.5, <redstonerepository:material:1>: 3.0 });
add(<redstonerepository:tool.sword_gelid>.withTag({ Energy: 0 }), { <redstonearsenal:material:32>: 1.0, <redstonerepository:material:1>: 1.0 });
add(<thaumadditions:adaminite_sword>, { <thaumadditions:adaminite_ingot>: 3.0, <thaumcraft:ingot:1>: 1.0 });
add(<thaumadditions:mithminite_belt>.withTag({ ench: [{ lvl: 1 as short, id: 28 }] }), { <minecraft:gold_ingot>: 0.25, <minecraft:iron_ingot>: 1.25, <thaumcraft:ingot:2>: 0.11111111111111113, <thaumcraft:ingot>: 1.0, <thermalfoundation:material:132>: 0.22222222222222227 });
add(<thaumadditions:mithminite_boots>.withTag({ ench: [{ lvl: 1 as short, id: 28 }] }), { <thaumcraft:ingot:1>: 3.5 });
add(<thaumadditions:mithminite_hood>.withTag({ ench: [{ lvl: 1 as short, id: 28 }] }), { <minecraft:gold_ingot>: 0.75, <thaumcraft:ingot:1>: 1.25, <thaumcraft:ingot>: 1.125, <thermalfoundation:material:128>: 2.0 });
add(<thaumadditions:void_elemental_axe:*>.withTag({ infench: [{ lvl: 1 as short, id: 2 as short }, { lvl: 1 as short, id: 0 as short }] }), { <thaumcraft:ingot:1>: 2.0 });
add(<thaumadditions:void_elemental_hoe:*>, { <thaumcraft:ingot:1>: 2.0, <thaumcraft:ingot>: 0.5 });
add(<thaumadditions:void_elemental_pickaxe:*>.withTag({ infench: [{ lvl: 1 as short, id: 4 as short }, { lvl: 2 as short, id: 3 as short }] }), { <thaumcraft:ingot:1>: 2.0, <thaumcraft:ingot>: 0.75 });
add(<thaumadditions:void_elemental_shovel:*>.withTag({ infench: [{ lvl: 1 as short, id: 1 as short }] }), { <thaumcraft:ingot:1>: 2.0 });
add(<thaumcraft:crimson_blade:*>, { <minecraft:netherbrick>: 1.0, <thaumadditions:mithminite_ingot>: 6.0, <thaumcraft:ingot:1>: 6.0, <thaumcraft:ingot>: 2.0 });
add(<thaumcraft:elemental_axe:*>.withTag({ infench: [{ lvl: 1 as short, id: 0 as short }, { lvl: 1 as short, id: 2 as short }] }), { <thaumcraft:ingot>: 1.5 });
add(<thaumcraft:elemental_hoe:*>, { <thaumcraft:ingot>: 1.0 });
add(<thaumcraft:elemental_pick:*>.withTag({ infench: [{ lvl: 1 as short, id: 4 as short }, { lvl: 2 as short, id: 3 as short }] }), { <thaumcraft:ingot>: 1.5 });
add(<thaumcraft:elemental_shovel:*>.withTag({ infench: [{ lvl: 1 as short, id: 1 as short }] }), { <thaumcraft:ingot>: 0.5 });
add(<thaumcraft:elemental_sword:*>.withTag({ infench: [{ lvl: 2 as short, id: 5 as short }] }), { <thaumcraft:ingot>: 1.0 });
add(<thaumcraft:fortress_chest:*>, { <minecraft:gold_ingot>: 1.0, <thaumcraft:ingot>: 8.0 });
add(<thaumcraft:fortress_helm:*>, { <minecraft:gold_ingot>: 2.0, <thaumcraft:ingot>: 4.5 });
add(<thaumcraft:fortress_legs:*>, { <minecraft:gold_ingot>: 1.0, <thaumcraft:ingot>: 6.5 });
add(<thaumcraft:goggles:*>, { <thaumcraft:ingot:2>: 2.0, <thermalfoundation:material:128>: 4.0 });
add(<thaumcraft:primal_crusher:*>.withTag({ infench: [{ lvl: 1 as short, id: 1 as short }, { lvl: 1 as short, id: 4 as short }] }), { <thaumcraft:ingot:1>: 2.0, <thaumcraft:ingot>: 0.75 });
add(<thaumcraft:thaumium_axe:*>, { <thaumcraft:ingot>: 3.0 });
add(<thaumcraft:thaumium_boots:*>, { <thaumcraft:ingot>: 5.0 });
add(<thaumcraft:thaumium_chest:*>, { <thaumcraft:ingot>: 8.0 });
add(<thaumcraft:thaumium_helm:*>, { <thaumcraft:ingot>: 5.0 });
add(<thaumcraft:thaumium_hoe:*>, { <thaumcraft:ingot>: 2.0 });
add(<thaumcraft:thaumium_legs:*>, { <thaumcraft:ingot>: 7.0 });
add(<thaumcraft:thaumium_pick:*>, { <thaumcraft:ingot>: 3.0 });
add(<thaumcraft:thaumium_shovel:*>, { <thaumcraft:ingot>: 1.0 });
add(<thaumcraft:thaumium_sword:*>, { <thaumcraft:ingot>: 2.0 });
add(<thaumcraft:void_axe:*>, { <thaumcraft:ingot:1>: 3.0 });
add(<thaumcraft:void_boots:*>, { <thaumcraft:ingot:1>: 5.0 });
add(<thaumcraft:void_chest:*>, { <thaumcraft:ingot:1>: 8.0 });
add(<thaumcraft:void_helm:*>, { <thaumcraft:ingot:1>: 5.0 });
add(<thaumcraft:void_hoe:*>, { <thaumcraft:ingot:1>: 2.0 });
add(<thaumcraft:void_legs:*>, { <thaumcraft:ingot:1>: 7.0 });
add(<thaumcraft:void_pick:*>, { <thaumcraft:ingot:1>: 3.0 });
add(<thaumcraft:void_robe_chest:*>, { <thaumcraft:ingot:1>: 4.0, <thaumcraft:ingot>: 1.0 });
add(<thaumcraft:void_robe_helm:*>, { <thaumcraft:ingot:1>: 3.0, <thaumcraft:ingot>: 0.5 });
add(<thaumcraft:void_robe_legs:*>, { <thaumcraft:ingot:1>: 5.0, <thaumcraft:ingot:2>: 0.25, <thaumcraft:ingot>: 1.0 });
add(<thaumcraft:void_shovel:*>, { <thaumcraft:ingot:1>: 1.0 });
add(<thaumcraft:void_sword:*>, { <thaumcraft:ingot:1>: 2.0 });
add(<thaumicaugmentation:primal_cutter:*>.withTag({ infench: [{ lvl: 2 as short, id: 5 as short }, { lvl: 1 as short, id: 2 as short }] }), { <thaumcraft:ingot:1>: 2.5 });
add(<thaumicaugmentation:thaumium_robes_chestplate:*>, { <thaumcraft:ingot>: 2.0 });
add(<thaumicaugmentation:thaumium_robes_hood:*>, { <thaumcraft:ingot:2>: 1.0, <thaumcraft:ingot>: 1.0, <thermalfoundation:material:128>: 2.0 });
add(<thaumicaugmentation:thaumium_robes_leggings:*>, { <thaumcraft:ingot:2>: 0.5, <thaumcraft:ingot>: 2.0 });
add(<thaumicaugmentation:void_boots:*>, { <thaumcraft:ingot:1>: 2.0, <thaumcraft:quicksilver>: 1.0 });
add(<thaumicwonders:night_vision_goggles:*>, { <minecraft:gold_ingot>: 0.44444444444444453, <thaumcraft:ingot:2>: 1.0, <thermalfoundation:material:128>: 2.0 });
add(<thaumicwonders:primal_destroyer:*>.withTag({ infench: [{ lvl: 3 as short, id: 6 as short }, { lvl: 2 as short, id: 14 as short }] }), { <thaumcraft:ingot:1>: 2.0 });
add(<thaumicwonders:void_fortress_chest:*>, { <minecraft:gold_ingot>: 0.5, <thaumcraft:ingot:1>: 4.0, <thaumcraft:ingot>: 2.0 });
add(<thaumicwonders:void_fortress_helm:*>, { <minecraft:gold_ingot>: 1.0, <thaumcraft:ingot:1>: 2.5, <thaumcraft:ingot>: 2.25 });
add(<thaumicwonders:void_fortress_legs:*>, { <minecraft:gold_ingot>: 0.5, <thaumcraft:ingot:1>: 3.5, <thaumcraft:ingot>: 3.25 });
add(<twilightforest:block_and_chain:*>, { <twilightforest:knightmetal_ingot>: 14.0 });
add(<twilightforest:fiery_sword:*>.withTag({ ench: [{ lvl: 2 as short, id: 20 as short }] }), { <twilightforest:fiery_ingot>: 2.0 });
add(<twilightforest:ironwood_axe:*>.withTag({ ench: [{ lvl: 1 as short, id: 35 as short }] }), { <twilightforest:ironwood_ingot>: 3.0 });
add(<twilightforest:ironwood_boots:*>, { <twilightforest:ironwood_ingot>: 5.0 });
add(<twilightforest:ironwood_chestplate:*>, { <twilightforest:ironwood_ingot>: 8.0 });
add(<twilightforest:ironwood_helmet:*>, { <twilightforest:ironwood_ingot>: 5.0 });
add(<twilightforest:ironwood_hoe:*>, { <twilightforest:ironwood_ingot>: 2.0 });
add(<twilightforest:ironwood_leggings:*>, { <twilightforest:ironwood_ingot>: 7.0 });
add(<twilightforest:ironwood_pickaxe:*>.withTag({ ench: [{ lvl: 1 as short, id: 32 as short }] }), { <twilightforest:ironwood_ingot>: 3.0 });
add(<twilightforest:ironwood_shovel:*>.withTag({ ench: [{ lvl: 1 as short, id: 34 as short }] }), { <twilightforest:ironwood_ingot>: 1.0 });
add(<twilightforest:ironwood_sword:*>.withTag({ ench: [{ lvl: 1 as short, id: 19 as short }] }), { <twilightforest:ironwood_ingot>: 2.0 });
add(<twilightforest:knightmetal_axe:*>, { <twilightforest:knightmetal_ingot>: 3.0 });
add(<twilightforest:knightmetal_pickaxe:*>, { <twilightforest:knightmetal_ingot>: 3.0 });
add(<twilightforest:knightmetal_sword:*>, { <twilightforest:knightmetal_ingot>: 2.0 });
add(<twilightforest:steeleaf_axe:*>.withTag({ ench: [{ lvl: 2 as short, id: 32 as short }] }), { <twilightforest:steeleaf_ingot>: 3.0 });
add(<twilightforest:steeleaf_hoe:*>, { <twilightforest:steeleaf_ingot>: 2.0 });
add(<twilightforest:steeleaf_shovel:*>.withTag({ ench: [{ lvl: 2 as short, id: 32 as short }] }), { <twilightforest:steeleaf_ingot>: 1.0 });
add(<twilightforest:steeleaf_sword:*>.withTag({ ench: [{ lvl: 2 as short, id: 21 as short }] }), { <twilightforest:steeleaf_ingot>: 2.0 });

// Total recipes: 316
