#modloaded probezs zenutils
#loader mixin
#priority 3000

import native.net.minecraft.client.Minecraft;
import native.java.lang.Runnable;
import native.net.minecraftforge.fml.common.Loader;
import native.net.minecraftforge.fml.common.LoaderState;

// Runnable that performs the actual world load. Dispatched onto the client
// (main) thread via Minecraft.addScheduledTask — launchIntegratedServer MUST
// run on the main thread; calling it from the ProbeZS RMI worker thread
// hard-crashes the JVM. A zenClass that `extends Runnable` can be passed
// straight to the native addScheduledTask (ZenUtils coerces the instance to
// its Java wrapper); note ZenUtils does NOT expose `.wrapper` for java.lang
// types, and neither a function literal nor `.wrapper` casts to Runnable — a
// direct extended-instance pass is the working form.
zenClass JoinTask extends Runnable {
  var folder as string;
  zenConstructor(folder as string) {
    this.folder = folder;
  }

  function run() as void {
    print('probezs: auto-joining world "' ~ this.folder ~ '"');
    Minecraft.getMinecraft().launchIntegratedServer(this.folder, this.folder, null);
  }
}

zenClass Op {
  static onKeyword as function(string)string;

  // Auto-join marker: scripts/mixin/probezs/autojoin_marker.zs is
  // regenerated by PrismLauncher.launch() before every launch with the
  // target save name baked in as a literal (ZenScript native access
  // blacklists file I/O, but .zs source is freely re-read on boot). The
  // GUI mixin (gui.zs) calls this once the first screen is set up — GUI
  // init always runs on the main thread, so calling launchIntegratedServer
  // directly here is safe, no marshaling needed. autoJoinFired guards
  // against firing twice (every screen goes through the hooked method); a
  // mutable map is used since static fields are final at runtime.
  static autoJoinFired as string[string] = {};

  static tryAutoJoinWorld as function()void = function () as void {
    if (!isNull(Op.autoJoinFired['done'])) return;

    // FML's mod-loading *error* screen (duplicate mod, missing dependency) is
    // an ordinary GuiScreen too, and it is shown while no mod has been
    // constructed yet. Joining a world from there dies inside the first mod
    // hooking loadWorld (Gnetum NPEs on its still-null config) and buries the
    // readable FML error under a bogus crash report. AVAILABLE is reached at
    // the end of FML's init, just before the real main menu appears.
    if (!Loader.instance().hasReachedState(LoaderState.AVAILABLE)) return;

    val folderName = scripts.mixin.probezs.autojoin_marker.AutoJoinMarker.world.trim();
    if (folderName.length() == 0) return;

    Op.autoJoinFired['done'] = 'true';
    print('probezs: auto-joining world "' ~ folderName ~ '"');
    Minecraft.getMinecraft().launchIntegratedServer(folderName, folderName, null);
  };

  // Headless auto-join entry point, driven over the ProbeZS RMI bridge (see
  // reloadable.zs's `__cmd__:join:` branch and dev/lib/probezs.ts's
  // ensureAutoJoined). gui.zs is the intended boot-time path; this stays as
  // the fallback for a game already sitting at the menu (marker written after
  // launch, GUI mixin skipped). Unlike the GUI hook it can arrive on the RMI
  // worker thread, so it schedules the load onto the client thread and returns
  // immediately (the Node side polls the log for "joined the game").
  static requestAutoJoin as function()string = function () as string {
    val folderName = scripts.mixin.probezs.autojoin_marker.AutoJoinMarker.world.trim();
    if (folderName.length() == 0) return 'no-marker';
    if (!isNull(Op.autoJoinFired['done'])) return 'already-joined';
    Op.autoJoinFired['done'] = 'true';
    val task as Runnable = JoinTask(folderName);
    Minecraft.getMinecraft().addScheduledTask(task);
    return 'scheduled';
  };
}
